---
- name: apt-get update
  apt: update_cache=yes

- name: install aptitude
  apt: name=aptitude state=present

- name: aptitude safe-upgrade
  apt: upgrade=yes

- name: set timezone
  copy:
    content: "{{ common.timezone }}\n"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: update timezone

- name: install ntp
  apt: name=ntp state=present

- name: configure locales
  locale_gen: name=en_US.UTF-8 state=present

- name: install cron
  apt: name=cron state=present

- name: install apt https transport
  apt: name='apt-transport-https' state=present

- name: install systemd
  apt: name=systemd state=present

- name: install systemd-sysv
  apt: name='systemd-sysv' state=present
  notify: reboot

- name: install unattended-upgrades
  apt: name=unattended-upgrades state=present

- name: configure unattended-upgrades
  copy: src=20auto-upgrades dest=/etc/apt/apt.conf.d
